#!/usr/bin/env python3
"""Analyze controlled framing evaluator sensitivity.

Input should be an `experiment.py` behavior matrix produced from a controlled
framing fixed-response JSONL plus the manifest generated by
`build_controlled_framing_subset.py`.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", str(Path("figures/.matplotlib-cache").resolve()))
os.environ.setdefault("MPLBACKEND", "Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


DEFAULT_MATRIX = Path("outputs/subsets/controlled_framing_reuse_response_n300_heuristic_behavior_matrix.csv")
DEFAULT_MANIFEST = Path("outputs/subsets/controlled_framing_reuse_response_n300_manifest.csv")
DEFAULT_OUTDIR = Path("figures/controlled_framing_n300")

BEHAVIOR_COLUMNS = [
    "misinformation_detection",
    "framing_resistance",
    "claim_status_recognition",
    "error_rejection",
    "correction_accuracy",
    "evidence_grounding",
    "source_faithfulness",
    "hallucination_control",
    "uncertainty_handling",
    "uncertainty",
    "nei_uncertainty_failure_proxy",
    "refutes_correction_credit_proxy",
    "supports_status_failure_proxy",
]


def normalize_behavior(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    if "evaluator_variant" not in out.columns and "variant" in out.columns:
        out["evaluator_variant"] = out["variant"]
    if "target_model" not in out.columns and "model_name" in out.columns:
        out["target_model"] = out["model_name"]
    if "source_id" not in out.columns and "id" in out.columns:
        out["source_id"] = out["id"].astype(str).str.replace(r"::[^:]+$", "", regex=True)
    if "framing_style" not in out.columns and "id" in out.columns:
        out["framing_style"] = out["id"].astype(str).str.extract(r"::([^:]+)$", expand=False)
    for col in ["final_score"] + BEHAVIOR_COLUMNS:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")
    return out


def save_heatmap(df: pd.DataFrame, path: Path, title: str, cbar_label: str) -> None:
    if df.empty:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fig_width = max(8, 1.2 * len(df.columns) + 3)
    fig_height = max(4, 0.55 * len(df.index) + 2.5)
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    values = df.astype(float).to_numpy()
    im = ax.imshow(values, aspect="auto", cmap="coolwarm", vmin=-np.nanmax(np.abs(values)), vmax=np.nanmax(np.abs(values)))
    ax.set_title(title, fontsize=14, pad=12)
    ax.set_xticks(range(len(df.columns)))
    ax.set_xticklabels(df.columns, rotation=35, ha="right")
    ax.set_yticks(range(len(df.index)))
    ax.set_yticklabels(df.index)
    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            value = values[i, j]
            label = "NA" if np.isnan(value) else f"{value:.3f}"
            ax.text(j, i, label, ha="center", va="center", fontsize=8)
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label(cbar_label)
    fig.tight_layout()
    fig.savefig(path, dpi=220)
    plt.close(fig)


def score_shift_summary(df: pd.DataFrame) -> pd.DataFrame:
    key_cols = ["source_id", "target_model", "evaluator_variant"]
    if "final_score" not in df.columns:
        return pd.DataFrame()
    wide = df.pivot_table(index=key_cols, columns="framing_style", values="final_score", aggfunc="mean").reset_index()
    rows = []
    for framing in ["assertive", "authoritative"]:
        if "neutral" not in wide.columns or framing not in wide.columns:
            continue
        temp = wide.dropna(subset=["neutral", framing]).copy()
        if temp.empty:
            continue
        temp["score_shift"] = temp[framing] - temp["neutral"]
        temp["abs_score_shift"] = temp["score_shift"].abs()
        grouped = temp.groupby("evaluator_variant", dropna=False)
        for variant, group in grouped:
            rows.append(
                {
                    "evaluator_variant": variant,
                    "framing_comparison": f"{framing}_minus_neutral",
                    "paired_cases": len(group),
                    "mean_score_shift": group["score_shift"].mean(),
                    "mean_abs_score_shift": group["abs_score_shift"].mean(),
                    "median_abs_score_shift": group["abs_score_shift"].median(),
                    "max_abs_score_shift": group["abs_score_shift"].max(),
                    "neutral_vs_framed_spearman": group[["neutral", framing]].corr(method="spearman").iloc[0, 1],
                }
            )
    return pd.DataFrame(rows)


def construct_shift_summary(df: pd.DataFrame) -> pd.DataFrame:
    key_cols = ["source_id", "target_model", "evaluator_variant"]
    rows = []
    metric_cols = [col for col in BEHAVIOR_COLUMNS if col in df.columns]
    for metric in metric_cols:
        wide = df.pivot_table(index=key_cols, columns="framing_style", values=metric, aggfunc="mean").reset_index()
        for framing in ["assertive", "authoritative"]:
            if "neutral" not in wide.columns or framing not in wide.columns:
                continue
            temp = wide.dropna(subset=["neutral", framing]).copy()
            if temp.empty:
                continue
            temp["shift"] = temp[framing] - temp["neutral"]
            for variant, group in temp.groupby("evaluator_variant", dropna=False):
                rows.append(
                    {
                        "evaluator_variant": variant,
                        "construct": metric,
                        "framing_comparison": f"{framing}_minus_neutral",
                        "paired_cases": len(group),
                        "mean_shift": group["shift"].mean(),
                        "mean_abs_shift": group["shift"].abs().mean(),
                    }
                )
    return pd.DataFrame(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--behavior-matrix", type=Path, default=DEFAULT_MATRIX)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTDIR)
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    behavior = normalize_behavior(pd.read_csv(args.behavior_matrix))
    manifest = pd.read_csv(args.manifest)
    merge_keys = ["target_model", "id"] if "target_model" in manifest.columns and "target_model" in behavior.columns else ["id"]
    merged = behavior.merge(
        manifest[[*merge_keys, "source_id", "framing_style", "subset_name", "subset_type"]],
        on=merge_keys,
        how="left",
        suffixes=("", "_manifest"),
        validate="many_to_one",
    )
    for col in ["source_id", "framing_style"]:
        fallback = f"{col}_manifest"
        if fallback in merged.columns:
            merged[col] = merged[col].fillna(merged[fallback])
    merged.to_csv(args.output_dir / "controlled_framing_behavior_with_manifest.csv", index=False)

    score_summary = score_shift_summary(merged)
    score_summary.to_csv(args.output_dir / "framing_score_shift_summary.csv", index=False)

    construct_summary = construct_shift_summary(merged)
    construct_summary.to_csv(args.output_dir / "framing_construct_shift_summary.csv", index=False)

    if not score_summary.empty:
        score_view = score_summary.pivot_table(
            index="evaluator_variant",
            columns="framing_comparison",
            values="mean_abs_score_shift",
            aggfunc="mean",
        )
        save_heatmap(
            score_view,
            args.output_dir / "framing_mean_abs_score_shift_heatmap.png",
            "Controlled Framing Mean Absolute Score Shift",
            "mean abs score shift",
        )

    if not construct_summary.empty:
        construct_view = construct_summary.pivot_table(
            index=["evaluator_variant", "construct"],
            columns="framing_comparison",
            values="mean_abs_shift",
            aggfunc="mean",
        )
        save_heatmap(
            construct_view,
            args.output_dir / "framing_construct_mean_abs_shift_heatmap.png",
            "Controlled Framing Construct Sensitivity",
            "mean abs construct shift",
        )

    print(f"Wrote controlled framing analysis to {args.output_dir}")
    if not score_summary.empty:
        print(score_summary.round(4).to_string(index=False))


if __name__ == "__main__":
    main()
